name: CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        default: "latest"
        required: false

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run generate & publish
        run: ZIG_VERSION=${{ inputs.version }} bun generate.ts --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
